spring:
    application:
        name: api-reuso
    datasource:
        url: jdbc:mysql://localhost:3306/db_reuso
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
    
app:
    url:
        dashboard: file:///C:/Users/pcnov/Documents/estudo/reuso/workshop-hub/static/overview.html